Integrate CodeRx MDT maintenance_inhaler submodule into asthma module
synthetichealth/synthea pull request #1182
Opened 2022-10-24 13:12 UTC by jrlegrand

Resolves #1181 

Created a `maintenance_inhaler` submodule following the CodeRx Medication Diversification Tool (MDT) tip sheet at https://coderx.io/projects/medication-diversification#tip-sheet.

Integrated the submodule into Synthea.

Ran a population of 5000 patients in Synthea and examined the CSV output to verify the diversity of maintenance inhaler medications having REASONDESCRIPTION "Asthma" / "Childhood Asthma" has increased from one to many.

Attaching the log file output ([log 20221024-062521.txt](https://github.com/synthetichealth/synthea/files/9851851/log.20221024-062521.txt)) from the [CodeRx Medication Diversification Tool (MDT)](https://github.com/coderxio/medication-diversification) - it helps summarize the expected distributions of  medication products at a population level and also provides a snapshot of the settings used to create this MDT submodule.

This is the first submission using the [CodeRx Medication Diversification Tool (MDT)](https://github.com/coderxio/medication-diversification) but we plan on submitting several more in the near future!

2022-10-25 20:50 UTC, jawalonoski commented
Thank you for the pull request! Clinical review was good, so we'll do some technical checks and then merge this in soon.

2022-10-26 14:40 UTC, jawalonoski commented
Looks like some of the unit tests broke:

```
Caused by:
[2254](https://github.com/synthetichealth/synthea/actions/runs/3312999002/jobs/5475000835#step:6:2255)
        java.lang.IllegalArgumentException: resource modules/lookup_tables/maintenance_inhaler_Beclomethasone_product_distribution.csv not found.
```

Looking into the cause...

2022-10-26 16:05 UTC, jrlegrand commented
I think the B in Beclomethasone got capitalized when it should be all lower case. Prob something that could be fixed in MDT but also could be fixed here to make the PR work. I'm traveling now but just wanted to point this out.

2022-10-27 15:28 UTC, jawalonoski commented
> I think the B in Beclomethasone got capitalized when it should be all lower case. Prob something that could be fixed in MDT but also could be fixed here to make the PR work. I'm traveling now but just wanted to point this out.

The case does appear to be the issue, but I can't recreate the test failure on either Mac OS X or Windows... and data generation on both platforms also works as expected... yet it fails consistently on the build.

2022-10-27 15:35 UTC, dehall commented
I think it's a difference in file system case sensitivity. Some file systems will consider "file.txt" and "File.txt" to be the same but others consider them different. I seem to remember seeing this with some MDT modules I've experimented with as well - the lookup table files are named with capitals in some places but are referenced in the modules with lower case.

2022-10-27 16:10 UTC, jawalonoski requested changes
It looks like the build environment file names are case-sensitive. I recommend that you keep the all-lowercase filenames and change the JSON lookups to be all-lowercase as well.

2022-10-27 16:10 UTC, jawalonoski commented on src/main/resources/modules/medications/maintenance_inhaler.json
> +                    "lookup_table_name": "maintenance_inhaler_Beclomethasone_product_distribution.csv"
```suggestion
                    "lookup_table_name": "maintenance_inhaler_beclomethasone_product_distribution.csv"
```

2022-10-27 16:10 UTC, jawalonoski commented on src/main/resources/modules/medications/maintenance_inhaler.json
> +                    "lookup_table_name": "maintenance_inhaler_Beclomethasone_product_distribution.csv"
```suggestion
                    "lookup_table_name": "maintenance_inhaler_beclomethasone_product_distribution.csv"
```

2022-10-27 16:10 UTC, jawalonoski commented on src/main/resources/modules/medications/maintenance_inhaler.json
> +                    "lookup_table_name": "maintenance_inhaler_Budesonide_product_distribution.csv"
```suggestion
                    "lookup_table_name": "maintenance_inhaler_budesonide_product_distribution.csv"
```

2022-10-27 16:10 UTC, jawalonoski commented on src/main/resources/modules/medications/maintenance_inhaler.json
> +                    "lookup_table_name": "maintenance_inhaler_Budesonide_product_distribution.csv"
```suggestion
                    "lookup_table_name": "maintenance_inhaler_budesonide_product_distribution.csv"
```

2022-10-27 16:10 UTC, jawalonoski commented on src/main/resources/modules/medications/maintenance_inhaler.json
> +                    "lookup_table_name": "maintenance_inhaler_Budesonide_product_distribution.csv"
```suggestion
                    "lookup_table_name": "maintenance_inhaler_budesonide_product_distribution.csv"
```

2022-10-27 16:10 UTC, jawalonoski commented on src/main/resources/modules/medications/maintenance_inhaler.json
> +                    "lookup_table_name": "maintenance_inhaler_Budesonide_product_distribution.csv"
```suggestion
                    "lookup_table_name": "maintenance_inhaler_budesonide_product_distribution.csv"
```

2022-10-27 16:10 UTC, jawalonoski commented on src/main/resources/modules/medications/maintenance_inhaler.json
> +                    "lookup_table_name": "maintenance_inhaler_Budesonide_product_distribution.csv"
```suggestion
                    "lookup_table_name": "maintenance_inhaler_budesonide_product_distribution.csv"
```

2022-10-27 16:10 UTC, jawalonoski commented on src/main/resources/modules/medications/maintenance_inhaler.json
> +                    "lookup_table_name": "maintenance_inhaler_Budesonide_product_distribution.csv"
```suggestion
                    "lookup_table_name": "maintenance_inhaler_budesonide_product_distribution.csv"
```

2022-10-27 16:10 UTC, jawalonoski commented on src/main/resources/modules/medications/maintenance_inhaler.json
> +                    "lookup_table_name": "maintenance_inhaler_Fluticasone_product_distribution.csv"
```suggestion
                    "lookup_table_name": "maintenance_inhaler_fluticasone_product_distribution.csv"
```

2022-10-27 16:10 UTC, jawalonoski commented on src/main/resources/modules/medications/maintenance_inhaler.json
> +                    "lookup_table_name": "maintenance_inhaler_Fluticasone_product_distribution.csv"
```suggestion
                    "lookup_table_name": "maintenance_inhaler_fluticasone_product_distribution.csv"
```

2022-10-27 16:10 UTC, jawalonoski commented on src/main/resources/modules/medications/maintenance_inhaler.json
> +                    "lookup_table_name": "maintenance_inhaler_Fluticasone_product_distribution.csv"
```suggestion
                    "lookup_table_name": "maintenance_inhaler_fluticasone_product_distribution.csv"
```

2022-10-27 16:10 UTC, jawalonoski commented on src/main/resources/modules/medications/maintenance_inhaler.json
> +                    "lookup_table_name": "maintenance_inhaler_Fluticasone_product_distribution.csv"
```suggestion
                    "lookup_table_name": "maintenance_inhaler_fluticasone_product_distribution.csv"
```

2022-10-27 16:10 UTC, jawalonoski commented on src/main/resources/modules/medications/maintenance_inhaler.json
> +                    "lookup_table_name": "maintenance_inhaler_Fluticasone_product_distribution.csv"
```suggestion
                    "lookup_table_name": "maintenance_inhaler_fluticasone_product_distribution.csv"
```

2022-10-27 16:10 UTC, jawalonoski commented on src/main/resources/modules/medications/maintenance_inhaler.json
> +                    "lookup_table_name": "maintenance_inhaler_Fluticasone_product_distribution.csv"
```suggestion
                    "lookup_table_name": "maintenance_inhaler_fluticasone_product_distribution.csv"
```

2022-10-27 16:10 UTC, jawalonoski commented on src/main/resources/modules/medications/maintenance_inhaler.json
> +                    "lookup_table_name": "maintenance_inhaler_Fluticasone_product_distribution.csv"
```suggestion
                    "lookup_table_name": "maintenance_inhaler_fluticasone_product_distribution.csv"
```

2022-10-27 16:10 UTC, jawalonoski commented on src/main/resources/modules/medications/maintenance_inhaler.json
> +                    "lookup_table_name": "maintenance_inhaler_Fluticasone_product_distribution.csv"
```suggestion
                    "lookup_table_name": "maintenance_inhaler_fluticasone_product_distribution.csv"
```

2022-10-27 16:10 UTC, jawalonoski commented on src/main/resources/modules/medications/maintenance_inhaler.json
> +                    "lookup_table_name": "maintenance_inhaler_Mometasone_product_distribution.csv"
```suggestion
                    "lookup_table_name": "maintenance_inhaler_mometasone_product_distribution.csv"
```

2022-10-27 16:10 UTC, jawalonoski commented on src/main/resources/modules/medications/maintenance_inhaler.json
> +                    "lookup_table_name": "maintenance_inhaler_Mometasone_product_distribution.csv"
```suggestion
                    "lookup_table_name": "maintenance_inhaler_mometasone_product_distribution.csv"
```

2022-10-27 16:10 UTC, jawalonoski commented on src/main/resources/modules/medications/maintenance_inhaler.json
> +                    "lookup_table_name": "maintenance_inhaler_Mometasone_product_distribution.csv"
```suggestion
                    "lookup_table_name": "maintenance_inhaler_mometasone_product_distribution.csv"
```

2022-10-27 16:10 UTC, jawalonoski commented on src/main/resources/modules/medications/maintenance_inhaler.json
> +                    "lookup_table_name": "maintenance_inhaler_Mometasone_product_distribution.csv"
```suggestion
                    "lookup_table_name": "maintenance_inhaler_mometasone_product_distribution.csv"
```

2022-10-31 14:33 UTC, merged