Support different distribution types for random variables in a new GMF format
synthetichealth/synthea pull request #788
Opened 2020-09-11 20:26 UTC by eedrummer

This change supports a new `distribution` property in `Delay`, `Observation`, `Procedure`, `SetAttribute`, `Symptom` and `VitalSign` states. 

For example, an `Observation` of LDL Cholesterol with a Gaussian distribution of results would be:

```json
    "Observation" : {
      "type" : "Observation",
      "category" : "procedure",
      "codes" : [
        {
          "system" : "LOINC",
          "code" : "2089-1",
          "display" : "Cholesterol in LDL"
        }
      ],
      "distribution": {
        "kind": "GAUSSIAN",
        "parameters": {
          "mean": 140,
          "standardDeviation": 15
        }
      },
      "unit": "mg/dL",
    }
```

All states still support the "legacy" format for defining ranges or whatever they call themselves. Current distribution types in this PR are:
* Exact
* Uniform
* Gaussian

The Distribution class should make it easy to add any other distribution types desired.

2020-09-17 20:08 UTC, dehall reviewed
Haven't tested yet but just looking at the code everything seems good, will test it out shortly. One potential idea - currently this is checking for "isLegagyGMF" every time the given state processes, and falls back to legacy behavior if it is. It's only a simple null check so not computationally intensive, but would it simplify things at all to instead "upgrade" the module at initialize time into the latest format?

2020-09-23 13:08 UTC, hadleynet requested changes

2020-09-25 13:28 UTC, hadleynet commented on src/main/java/org/mitre/synthea/engine/State.java
> +        this.stop = procedure.start + Utilities.convertTime(procedureDurationUnit,
Will fix this separately.

2020-10-02 14:22 UTC, eedrummer commented
The changes that @hadleynet made look good to me. I like @dehall 's idea about up converting GMF 1.0 states on loading the JSON, as that would allow us to get rid of GMF 1.0 code everywhere but the initialization code, but I don't know if we want to take that on right now.

@jawalonoski I know you don't have a lot of time to look at this, but it would be great to get your thoughts.

2021-02-10 16:35 UTC, hadleynet requested changes
Two small changes in your clone methods.

2021-02-10 16:35 UTC, hadleynet commented on src/main/java/org/mitre/synthea/engine/State.java
> +      clone.symptom = symptom;
Same comment re super.clone doing the work of copying members.

2021-02-10 16:35 UTC, hadleynet commented on src/main/java/org/mitre/synthea/engine/State.java
> +      clone.codes = codes;
I think the super.clone will take care of copying all of the member variables so you can remove lines 1401-1406 inclusive.

2021-02-10 18:37 UTC, eedrummer commented
@hadleynet I cleaned up the clone methods. I think some of that was pulled back in by the rebase I did off of master and not correctly resolving the conflict.

2021-02-10 22:02 UTC, hadleynet approved these changes

2021-02-23 20:36 UTC, merged